### PR TITLE
installed and configured gatsby-source-github-repo plugin

### PR DESCRIPTION
**Pull request by dakebl**
installed and configure gatsby-source-github-repo, and removed old manual logic.

### CODE REVIEW

**Comment by domyen** [comment]
Stoked for this! Let us know when this PR is ready for review 👌

**Comment by dakebl** [comment]
@domyen Should be good to review now 🙏

**Comment by domyen** [comment]
The `Hero` and `TeamScreen` components should also be updated to use this new methodology because they rely on this stat as well. This [old commit](https://github.com/storybooks/frontpage/commit/e4b4badb544fb7b48f582e79d205c16b83309e16) did it in the previous way.

**Comment by dakebl** [comment]
@domyen I've updated the remaining components and it's ready to test again 😉

**Comment by dakebl** [comment]
Push one more commit to move over the urls for stargazer, as well as `ContributorItem`. Should be all done now 🤞

**Pull request merged**
