### PR TITLE
9 gatsby best practices audit

### PR DESCRIPTION
**Pull request by dakebl**
This PR addresses issue #9 by implementing some of the suggestions made by @jlengstorf:

https://github.com/storybooks/frontpage/issues/9#issuecomment-471087113
> Hey! 👋
> 
> One quick win would be to use `gatsby-image` for the benefit images (e.g. [here](https://github.com/storybooks/frontpage/blob/f144fedbb95d003d0eb9403a16db98c799fec43a/src/components/screens/IndexScreen/IndexScreen.js#L73)).
> 
> Another thing that you _could_ do (though it’s certainly not required) is to add your config info to the `gatsby-config.js` as site metadata. This makes it queryable in GraphQL and has the benefit of centralizing all of the site config so future maintainers know where to look for it. One candidate would be https://github.com/storybooks/frontpage/blob/master/src/components/basics/shared/site.js — for reference, here’s how I manage site metadata on [my personal site](https://github.com/jlengstorf/lengstorf.com/blob/c1b0f7cf91210e84fbaa90561d33e4f9143e522c/gatsby-config.js#L66-L128).
> 
> To eliminate extra requests, you can inline SVGs by importing them. For example, in [this component](https://github.com/storybooks/frontpage/blob/f144fedbb95d003d0eb9403a16db98c799fec43a/src/components/layout/Header.js#L156) you could directly import the SVG
> instead. ([Example](https://github.com/jlengstorf/lengstorf.com/blob/c1b0f7cf91210e84fbaa90561d33e4f9143e522c/src/components/Beard.js#L4))
> 
> Overall this looks _really_ good. Excellent work!
> 
> Let me know if I can do anything else to help.

The PR includes:
- Moving site metadata (mainly link values) into `gatsby-config.js`.
- Changing the SVG loading logic to use direct imports, rather than relative url paths to the `static` directory.

### CODE REVIEW

**Comment by domyen** [comment]
Incredible work @dakebl! Thank you! 

✅I reviewed the changes in Chromatic
✅Code lgtm

Will pull in @tmeasday for a quick skim.

**Comment by domyen** [comment]
Heads up `master` now lints! The CI workflow fails on errors and warnings. Will fix them now.

**Comment by dakebl** [comment]
Thanks for updating @domyen!

I took a look at the failing workflow on Circle CI and, after a little digging around, I found that @shilman had addressed the underlying issue (a problem with module hoisting) in a recent alpha release ([v5.1.0-alpha.23](https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.23)) of Storybook.

I've updated the versions in the `package.json`, regenerated both the `package-lock.json` and `yarn.lock` files, and it's now passing.

Could you take a look at the chromatic tests again please?

**Comment by domyen** [comment]
LGTM. Thanks for fixing the brokenness!

**Pull request merged**
